### ISSUE TITLE
Tối ưu dòng code này

### ISSUE THREAD

**Issue by yopaz-giapnh** [anhuv/demo#4]
https://github.com/ungvietanh20172394/demo/blob/ddb7410e6dae5aa9b8adcf2b181e2c8cc6deebc3/routes/sensor.py#L69

**Comment by anhuv** [comment]
db.query(models.Record).delete().where(Record.sensor_id==id_sensor)
Câu này em chưa chắc chắn, nếu anh thấy tạm ổn rồi close giúp em nhé, còn chưa được thì em cần thời gian suy nghĩ thêm.
